### ISSUE TITLE
 Buffer is not defined

### ISSUE THREAD

**Issue by acmeid** [bitcoinjs/tiny-secp256k1#100] opened 2022-12-12 10:36 UTC
An error is reported in the browser:
```
Uncaught ReferenceError: Buffer is not defined
    at ./node_modules/tiny-secp256k1/rfc6979.js (rfc6979.js:3:1)
```

**Comment by junderw** [comment] 2022-12-12 13:05
Duplicate of #47 

Webpack removed automatic Buffer support, and you need to add the Buffer inclusion explicitly in your config file.

Please check your bundler's documentation about the NodeJS Buffer API and it should help you include Buffer.

**Closed by junderw** 2022-12-12 13:05 UTC
